name: example_dart_cryptographic_license_files
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies: {args: ^2.3.1, convert: ^3.0.2, crypto: ^3.0.2, cryptography: ^2.0.5, http: ^0.13.5, io: ^1.0.3  , dotenv: ^4.0.1 , uuid: ^3.0.6, postgres: ^2.5.2}
